# Generated by Django 4.2.3 on 2023-10-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
