# Generated by Django 4.2.3 on 2023-10-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productreview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.CharField(default='', max_length=300),
        ),
    ]
