# Generated by Django 4.2.3 on 2023-09-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'deposit'), (2, 'withdraw'), (3, 'loan'), (4, 'loan_paid')], null=True),
        ),
    ]
