# Generated by Django 4.2.3 on 2023-08-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('grade', models.FloatField()),
            ],
        ),
    ]
