# Generated by Django 4.2.3 on 2023-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='address',
            field=models.CharField(default='Dhaka', max_length=30),
        ),
    ]
