# Generated by Django 4.2.3 on 2023-08-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(related_name='teachers', to='first_app.student'),
        ),
    ]
