# Generated by Django 4.2.3 on 2023-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_market_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('trade_code', models.CharField(max_length=30)),
                ('high', models.DecimalField(decimal_places=1, max_digits=2)),
                ('low', models.DecimalField(decimal_places=1, max_digits=2)),
                ('open_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('close', models.DecimalField(decimal_places=1, max_digits=2)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
