# Generated by Django 4.2.3 on 2023-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_market_model',
            name='date',
            field=models.DateField(),
        ),
    ]
