# Generated by Django 4.2.3 on 2023-09-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0002_alter_stock_market_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_market_model',
            name='close',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock_market_model',
            name='high',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock_market_model',
            name='low',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock_market_model',
            name='open_value',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock_market_model',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
