# Generated by Django 4.2.3 on 2023-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0003_alter_stock_market_model_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_market_model',
            name='close',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_market_model',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_market_model',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_market_model',
            name='open_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_market_model',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
