# Generated by Django 4.2.3 on 2023-09-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0004_alter_stock_market_model_close_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_market_model',
            old_name='open_value',
            new_name='open',
        ),
    ]
